package jp.gr.java_conf.keln;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class DataProcessor {
	
	private KELN keln;
	
	public DataProcessor(KELN keln){
		this.keln = keln;
	}
	
	public static String replaceString(String str, String match, String replace){
		String regex = match;
		Pattern p = Pattern.compile(regex);
		Matcher m = p.matcher(str);
		String result = m.replaceAll(replace);
		return result;
	}
	
	
	public String getHTML(String author, String month, String date, String title,
									ArrayList<String> namelist, ArrayList<String> header, String memo,
									ArrayList<ArrayList<String>> table){ //Convert JTable into HTML format
		String out = "";
		
		//Author
		out += "<!-- Table Generated by KELN" + " ";
		out += "Author: " + author;
		out += " -->\r\n<div class=\"keln_container\">\r\n";
		//Date
		out += "<a name=\"";
		if(Integer.parseInt(month) <= 9){
			out += "0";
		}
		out += month;
		try{
			if(Integer.parseInt(date) <= 9){
				out += "0";
			}
		}catch(NumberFormatException e){
			JOptionPane.showMessageDialog(keln, "Date is invalid or empty.");
			return "error";
		}
		out += date;
		out += "\" class = \"kyoto-jump\"></a>\r\n";
		out += "<span class=\"keln_date\"><h3>";
		out += month + "/" + date;
		out += "</h3></span>\r\n";
		
		//Experiment name
		out += "<span class=\"keln_exp\"><h4>";
		out += title;
		out += "</h4></span>\r\n";
		
		//Experimenter name
		out += "<span class=\"keln_researcher\">";
		
		int len_namelist = namelist.size();
		for(int i=0; i<namelist.size(); i++){
			out += namelist.get(i);
			if(i < len_namelist - 1) {
				out += ", "; //Do not add comma after the last name
			}
		}
		
		out += "</span>\r\n";
		
		//Table start
		out += "<table class=\"keln_table\">\r\n";
		
		//Add header
		out += "<tr>";
		for (String string : header) {
			out += "<th>" + string + "</th>";
		}
		out += "</tr>\r\n";
		
		for(int i=0; i<table.size(); i++) {
			out += "<tr>";
			for(int j=0; j<table.get(0).size(); j++) {
				out += "<td>" + table.get(i).get(j) + "</td>";
			}
			out += "</tr>\r\n";
		}
		out += "</table>\r\n</div>\r\n";
		
		if(!memo.equals("")){
			memo = replaceString(memo, "\n", "<br>");
			out += "<p class=\"keln_note\">" + memo + "</p>" + "\n";
		}
		out += "<!------------ Table END ------------>";
		out = replaceString(out, "É ", "&micro");
		return out;
	}
}
